/// https://html.spec.whatwg.org/multipage/parsing.html#parse-errors
pub const HTMLParserErrors = error{
    ControlCharacterInInputStream,
    EOFInCdata,
    EOFInComment,
    EOFInDoctype,
    EOFInScriptHtmlCommentLikeText,
    EOFInTag,
    InvalidCharacterSequenceAfterDoctypeName,
    NoncharacterInInputStream,
    SurrogateInInputStream,
    MissingWhitespaceAfterDoctypePublicKeyword,
    MissingWhitespaceAfterDoctypeSystemKeyword,
    MissingWhitespaceBetweenDoctypePublicAndSystemIdentifiers,
    MissingQuoteBeforeDoctypeSystemIdentifier,
    MissingDoctypePublicIdentifier,
    MissingDoctypeSystemIdentifier,
    MissingQuoteBeforeDoctypePublicIdentifier,
    UnexpectedNullCharacter,
    AbruptDoctypePublicIdentifier,
    AbruptDoctypeSystemIdentifier,
    UnexpectedCharacterAfterDoctypeSystemIdentifier,
};
